### ISSUE TITLE
TopNav should get hamburger in tablet mode

### ISSUE THREAD

**Issue by bryancostanich** [WildernessLabs/Documentation#77]
Right now it does this:

<img width="1047" alt="screen shot 2018-01-28 at 2 02 28 pm" src="https://user-images.githubusercontent.com/947633/35487758-08c7f84c-0434-11e8-9490-4cc1a6c8664e.png">

**Comment by stephenkarpeles** [comment]
This is fixed...

**Comment by bryancostanich** [comment]
It gets a hamburger, but the menu doesn't work.

**Comment by stephenkarpeles** [comment]
I see that... reassigning to myself for now.

**Comment by stephenkarpeles** [comment]
Fixed on topnav

**Comment by bryancostanich** [comment]
hm. still not working for me. pulled latest, hard refreshed.

**Comment by stephenkarpeles** [comment]
Okay just pushed another change. Hopefully that works on your end as well...

**Comment by bryancostanich** [comment]
Working now. :)
